apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubernetes-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kubernetes-demo
  template:
    metadata:
      labels:
        app: kubernetes-demo
    spec:
      containers:
      - name: kubernetes-demo
        image: mycluster-registry.localhost:5000/kubernetes-demo:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3000
